/**
 * Bubble Sort — Trace questions & Solve problems
 *
 * Default array: [64, 34, 25, 12, 22, 11, 90]
 * Steps generated by generateBubbleSortSteps walk through passes and swaps.
 */

import type { TraceQuestion, SolveProblem } from "./binarySearchChallenges"

// Steps overview for [64, 34, 25, 12, 22, 11, 90]:
//   0: init
//   1: compare arr[0]=64 vs arr[1]=34
//   2: swap 64 and 34 → [34, 64, 25, ...]
//   3: compare arr[1]=64 vs arr[2]=25
//   4: swap 64 and 25 → [34, 25, 64, ...]
//   ... continues through passes

export const BUBBLE_SORT_TRACE_QUESTIONS: TraceQuestion[] = [
  {
    id: "bs-trace-1",
    pauseAfterStep: 0,
    text: "Bubble Sort starts. In the first pass, which direction do comparisons go?",
    options: [
      "Left to right, comparing adjacent pairs",
      "Right to left, comparing adjacent pairs",
      "From the middle outward",
      "Random comparisons",
    ],
    correct: 0,
    explanation: "Bubble Sort compares adjacent elements from left to right, swapping when the left element is larger.",
    xp: 25,
  },
  {
    id: "bs-trace-2",
    pauseAfterStep: 1,
    text: "We compare arr[0]=64 and arr[1]=34. Since 64 > 34, what happens?",
    options: [
      "Swap them — 34 moves left, 64 moves right",
      "Keep them — they're already sorted",
      "Remove the larger element",
      "Skip to the next pass",
    ],
    correct: 0,
    explanation: "64 > 34, so we swap. The larger value 'bubbles' to the right.",
    xp: 25,
  },
  {
    id: "bs-trace-3",
    pauseAfterStep: 5,
    text: "Several comparisons into pass 1. After a full pass, where does the largest unsorted element end up?",
    options: [
      "At the beginning of the array",
      "At its correct final position (rightmost unsorted slot)",
      "In the middle of the array",
      "It stays where it started",
    ],
    correct: 1,
    explanation: "Each pass 'bubbles' the largest unsorted element to its final position at the right end.",
    xp: 25,
  },
  {
    id: "bs-trace-4",
    pauseAfterStep: 10,
    text: "After multiple passes, the right portion of the array is sorted. Why does each new pass scan fewer elements?",
    options: [
      "Because sorted elements at the end don't need re-checking",
      "Because the array gets shorter",
      "Because we skip every other element",
      "It doesn't — we always scan the full array",
    ],
    correct: 0,
    explanation: "After pass i, the last i elements are in their final positions. We only need to compare the unsorted portion.",
    xp: 25,
  },
]

export const BUBBLE_SORT_SOLVE_PROBLEMS: SolveProblem[] = [
  {
    id: "bs-solve-1",
    array: [5, 3, 8, 1],
    target: 0,
    question: "After the FIRST complete pass of bubble sort on [5, 3, 8, 1], what is the array?",
    options: ["[3, 5, 1, 8]", "[1, 3, 5, 8]", "[3, 1, 5, 8]", "[5, 3, 1, 8]"],
    correct: 0,
    explanation: "Pass 1: 5>3→swap [3,5,8,1], 5<8→no swap, 8>1→swap [3,5,1,8]. The largest (8) bubbles to the end.",
    xp: 30,
  },
  {
    id: "bs-solve-2",
    array: [1, 2, 3, 4, 5],
    target: 0,
    question: "How many passes does optimized bubble sort need for the already-sorted array [1, 2, 3, 4, 5]?",
    options: ["4 passes", "1 pass", "5 passes", "0 passes"],
    correct: 1,
    explanation: "With the 'swapped' optimization, if no swaps occur in a pass, the array is sorted. One pass confirms this.",
    xp: 30,
  },
  {
    id: "bs-solve-3",
    array: [9, 7, 5, 3, 1],
    target: 0,
    question: "For a reverse-sorted array of 5 elements, what is the maximum number of swaps bubble sort performs?",
    options: ["5", "10", "4", "20"],
    correct: 1,
    explanation: "Worst case: n(n-1)/2 = 5×4/2 = 10 swaps. Every pair is out of order in a fully reversed array.",
    xp: 30,
  },
]

export const TRACE_TOTAL_XP = BUBBLE_SORT_TRACE_QUESTIONS.reduce((s, q) => s + q.xp, 0)
export const SOLVE_TOTAL_XP = BUBBLE_SORT_SOLVE_PROBLEMS.reduce((s, p) => s + p.xp, 0)
export const LEVEL_TOTAL_XP = TRACE_TOTAL_XP + SOLVE_TOTAL_XP
